**_Tensorflow Deep Learning_**


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [5]:
df = pd.read_csv("sports.csv")

In [6]:
df.head()

class id                 filepaths      labels data set
0         0  train/air hockey/001.jpg  air hockey    train
1         0  train/air hockey/002.jpg  air hockey    train
2         0  train/air hockey/003.jpg  air hockey    train
3         0  train/air hockey/004.jpg  air hockey    train
4         0  train/air hockey/005.jpg  air hockey    train

In [7]:
filepaths = ["Image Dataset/" + filepath for filepath in df["filepaths"]]

In [8]:
filepaths

['Image Dataset/train/air hockey/001.jpg',
 'Image Dataset/train/air hockey/002.jpg',
 'Image Dataset/train/air hockey/003.jpg',
 'Image Dataset/train/air hockey/004.jpg',
 'Image Dataset/train/air hockey/005.jpg',
 'Image Dataset/train/air hockey/006.jpg',
 'Image Dataset/train/air hockey/007.jpg',
 'Image Dataset/train/air hockey/008.jpg',
 'Image Dataset/train/air hockey/009.jpg',
 'Image Dataset/train/air hockey/010.jpg',
 'Image Dataset/train/air hockey/011.jpg',
 'Image Dataset/train/air hockey/012.jpg',
 'Image Dataset/train/air hockey/013.jpg',
 'Image Dataset/train/air hockey/014.jpg',
 'Image Dataset/train/air hockey/015.jpg',
 'Image Dataset/train/air hockey/016.jpg',
 'Image Dataset/train/air hockey/017.jpg',
 'Image Dataset/train/air hockey/018.jpg',
 'Image Dataset/train/air hockey/019.jpg',
 'Image Dataset/train/air hockey/020.jpg',
 'Image Dataset/train/air hockey/021.jpg',
 'Image Dataset/train/air hockey/022.jpg',
 'Image Dataset/train/air hockey/023.jpg',
 'Image Dat

In [9]:
len(filepaths)

14493

In [11]:
bool_labels = [df["labels"].unique() == label for label in df["labels"]]

In [12]:
bool_labels

[array([ True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False]),
 array([ True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, Fal

In [14]:
y = bool_labels

In [17]:
x = filepaths

In [18]:
x

['Image Dataset/train/air hockey/001.jpg',
 'Image Dataset/train/air hockey/002.jpg',
 'Image Dataset/train/air hockey/003.jpg',
 'Image Dataset/train/air hockey/004.jpg',
 'Image Dataset/train/air hockey/005.jpg',
 'Image Dataset/train/air hockey/006.jpg',
 'Image Dataset/train/air hockey/007.jpg',
 'Image Dataset/train/air hockey/008.jpg',
 'Image Dataset/train/air hockey/009.jpg',
 'Image Dataset/train/air hockey/010.jpg',
 'Image Dataset/train/air hockey/011.jpg',
 'Image Dataset/train/air hockey/012.jpg',
 'Image Dataset/train/air hockey/013.jpg',
 'Image Dataset/train/air hockey/014.jpg',
 'Image Dataset/train/air hockey/015.jpg',
 'Image Dataset/train/air hockey/016.jpg',
 'Image Dataset/train/air hockey/017.jpg',
 'Image Dataset/train/air hockey/018.jpg',
 'Image Dataset/train/air hockey/019.jpg',
 'Image Dataset/train/air hockey/020.jpg',
 'Image Dataset/train/air hockey/021.jpg',
 'Image Dataset/train/air hockey/022.jpg',
 'Image Dataset/train/air hockey/023.jpg',
 'Image Dat

In [19]:
y

[array([ True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False]),
 array([ True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, Fal

In [65]:
def process_image(filepath):
    img = tf.io.read_file(filepath)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.convert_image_dtype(img, tf.float32)
    img = tf.image.resize(img, (224, 224))
    return img

In [66]:
from IPython.display import Image, display

In [67]:
process_image(x[0])

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.4431373 , 0.28627452, 0.18823531],
        [0.21960786, 0.07450981, 0.        ],
        [0.18823531, 0.0627451 , 0.01960784],
        ...,
        [0.10196079, 0.10980393, 0.05490196],
        [0.08627451, 0.09019608, 0.06666667],
        [0.08627451, 0.09411766, 0.07450981]],

       [[0.48235297, 0.31764707, 0.21960786],
        [0.21960786, 0.07058824, 0.        ],
        [0.21176472, 0.08627451, 0.04313726],
        ...,
        [0.10196079, 0.10196079, 0.05490196],
        [0.10196079, 0.10588236, 0.07450981],
        [0.08627451, 0.09411766, 0.07450981]],

       [[0.49803925, 0.32156864, 0.20000002],
        [0.37647063, 0.21176472, 0.11764707],
        [0.24313727, 0.10196079, 0.04705883],
        ...,
        [0.10588236, 0.10588236, 0.05882353],
        [0.09803922, 0.10196079, 0.07058824],
        [0.08235294, 0.09411766, 0.06666667]],

       ...,

       [[0.16470589, 0.19215688, 0.37254903],
        [0.16

In [40]:
def get_label(filepath, label):
    return process_image(filepath), label

In [69]:
def create_batches(x, y=None, test_data=False, val_data=False):
    if test_data:
        data = tf.data.Dataset.from_tensor_slices(tf.constant(x))
        data = data.map(process_image).batch(32)
    elif val_data:
        data = tf.data.Dataset.from_tensor_slices((tf.constant(x), tf.constant(y)))
        data = data.map(process_image).batch(32)
    else:
        data = tf.data.Dataset.from_tensor_slices((tf.constant(x), tf.constant(y)))
        data = data.map(process_image).batch(32)
    return list(data.as_numpy_iterator())

In [75]:
data = tf.data.Dataset.from_tensor_slices(tf.constant(x))
data = data.map(process_image).batch(32)