Creating Deep Learning Model From Scratch Using Tensorflow Framework

1. Import necessary libraries

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_hub as hub

2. Get the data, preprocess it using `tf.keras.utils.image_dataset_from_directory` and for splitting it into batches.

In [56]:
data = tf.keras.utils.image_dataset_from_directory(
    "C:/Users/Vimal Manoharan/Desktop/AIML/Sample Images/Test",
    class_names=["boxing", "bowling", "cricket", "golf", "javelin"],
)

Found 25 files belonging to 5 classes.


3. View the preprocessed data using `as_numpy_iterator()`

In [57]:
data_iterator = data.as_numpy_iterator()

In [58]:
data_viewer = data_iterator.next()

In [59]:
data_viewer

(array([[[[0.00000000e+00, 0.00000000e+00, 2.00000000e+00],
          [0.00000000e+00, 0.00000000e+00, 2.00000000e+00],
          [0.00000000e+00, 0.00000000e+00, 2.00000000e+00],
          ...,
          [0.00000000e+00, 1.00000000e+00, 1.25000000e+00],
          [0.00000000e+00, 1.00000000e+00, 4.00000000e+00],
          [0.00000000e+00, 1.00000000e+00, 4.00000000e+00]],
 
         [[0.00000000e+00, 0.00000000e+00, 2.00000000e+00],
          [0.00000000e+00, 0.00000000e+00, 2.00000000e+00],
          [0.00000000e+00, 0.00000000e+00, 2.00000000e+00],
          ...,
          [0.00000000e+00, 7.46093750e-01, 7.42187500e-01],
          [0.00000000e+00, 3.39843750e-01, 2.37500000e+00],
          [0.00000000e+00, 1.00000000e+00, 2.37500000e+00]],
 
         [[6.87500000e-01, 6.87500000e-01, 2.68750000e+00],
          [1.28906250e-01, 1.28906250e-01, 2.12890625e+00],
          [0.00000000e+00, 0.00000000e+00, 2.00000000e+00],
          ...,
          [2.10546875e+00, 3.26562500e+00, 2.7734

In [60]:
len(data_viewer)  # Image Tensors and Image Labels

2

In [61]:
len(data_viewer[0])  # First Batch

25

In [62]:
data

<BatchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [63]:
data = data.map(
    lambda x, y: (x / 255.0, y)
)  # converting the numbers of tensors between 0 to 1. channels are 255

train_data = data

Now that the data has been preprocessed and split into batches of 32 images each. We can start building our model
1. Create a model (Sequential)
2. Compile the model
3. Train the model
4. Evaluate it

**Creation of a deep learning CNN model from scratch. We will implement `Transfer Learning` after this**

In [64]:
from tensorflow.keras import models, layers

In [65]:
model = models.Sequential(
    [
        tf.keras.layers.Conv2D(
            64, (4, 4), input_shape=(256, 256, 3), activation="relu"
        ),
        tf.keras.layers.MaxPool2D((2, 2)),
        tf.keras.layers.Conv2D(64, (4, 4), activation="relu"),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(5, activation="softmax"),
    ]
)

**Compiling our model**

In [66]:
model.compile(
    metrics=["accuracy"], optimizer="adam", loss="sparse_categorical_crossentropy"
)

**Fitting Our Model**

In [67]:
train_data

<MapDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [68]:
model.fit(train_data, epochs=5)

Epoch 1/5
1/1 [==============================] - 3s 3s/step - loss: 1.6087 - accuracy: 0.2000
Epoch 2/5
1/1 [==============================] - 3s 3s/step - loss: 12.5867 - accuracy: 0.3600
Epoch 3/5
1/1 [==============================] - 3s 3s/step - loss: 11.9415 - accuracy: 0.3200
Epoch 4/5
1/1 [==============================] - 2s 2s/step - loss: 9.9271 - accuracy: 0.4800
Epoch 5/5
1/1 [==============================] - 2s 2s/step - loss: 4.5975 - accuracy: 0.5600


**Now that the data has been fitted into our model and trained we can now evaluate model with the test data**

In [ ]:
test_data = tf.keras.utils.image_dataset_from_directory(
    "C:/Users/Vimal Manoharan/Desktop/AIML/Sample Images/Test"
)

Found 25 files belonging to 5 classes.


In [ ]:
model.evaluate(test_data)

1/1 [==============================] - 1s 1s/step - loss: 27.5926 - accuracy: 0.8400


[27.592622756958008, 0.8399999737739563]

**Model is working fine. Its balanced. Neither overfit nor umderfit cuz it has an accuracy of 1.0000 in training data while in test data it has accuracy of 0.84 which is decent. We have to now tune our model and try to improve it by experimenting with it**

In [ ]:
model.fit(train_data, epochs=10)

Epoch 1/10
21/21 [==============================] - 116s 5s/step - loss: 2.2242 - accuracy: 0.3040
Epoch 2/10
21/21 [==============================] - 96s 4s/step - loss: 1.2011 - accuracy: 0.4863
Epoch 3/10
21/21 [==============================] - 99s 5s/step - loss: 0.9867 - accuracy: 0.5912
Epoch 4/10
21/21 [==============================] - 100s 5s/step - loss: 0.6350 - accuracy: 0.7827
Epoch 5/10
21/21 [==============================] - 105s 5s/step - loss: 0.3932 - accuracy: 0.8647
Epoch 6/10
21/21 [==============================] - 114s 5s/step - loss: 0.1487 - accuracy: 0.9650
Epoch 7/10
21/21 [==============================] - 103s 5s/step - loss: 0.0436 - accuracy: 0.9939
Epoch 8/10
21/21 [==============================] - 97s 5s/step - loss: 0.0133 - accuracy: 1.0000
Epoch 9/10
21/21 [==============================] - 97s 5s/step - loss: 0.0185 - accuracy: 0.9954
Epoch 10/10
21/21 [==============================] - 124s 6s/step - loss: 0.0024 - accuracy: 1.0000


In [ ]:
model.save("firstdlm")

INFO:tensorflow:Assets written to: firstdlm\assets


INFO:tensorflow:Assets written to: firstdlm\assets


In [ ]:
model.evaluate(test_data)

1/1 [==============================] - 1s 1s/step - loss: 194.5350 - accuracy: 0.6000


[194.53500366210938, 0.6000000238418579]

In [ ]:
dataiter = train_data.as_numpy_iterator()

In [ ]:
batch1 = dataiter.next()

In [ ]:
len(batch1[0])

32

In [ ]:
model.predict(batch1[0])

1/1 [==============================] - 2s 2s/step


array([[1.58869971e-05, 2.88018782e-08, 9.99967754e-01, 9.38625453e-06,
        6.83846019e-06],
       [6.85769990e-02, 9.20977473e-01, 3.18214367e-03, 3.53388977e-03,
        3.72954970e-03],
       [7.95026077e-04, 2.41142243e-05, 3.54325213e-02, 9.63615596e-01,
        1.32720103e-04],
       [4.84284683e-05, 2.74780973e-06, 9.98839200e-01, 3.65866217e-05,
        1.07308186e-03],
       [1.60509003e-07, 3.28879790e-09, 9.99999702e-01, 1.07706690e-07,
        2.64124900e-08],
       [1.11306906e-02, 6.60203688e-04, 8.76614004e-02, 8.83782685e-01,
        1.67650338e-02],
       [1.05905187e-04, 1.55971222e-07, 3.95198149e-04, 9.99497712e-01,
        9.92805667e-07],
       [2.71198672e-07, 1.37667069e-08, 9.99983370e-01, 6.34211688e-07,
        1.57340819e-05],
       [9.99548972e-01, 9.99011390e-05, 3.52101961e-06, 2.15710941e-04,
        1.31856170e-04],
       [8.17254113e-05, 9.99901831e-01, 1.43518700e-05, 2.04569051e-06,
        4.19293080e-08],
       [1.36474491e-05, 3.2418

In [ ]:
batch1[1]

array([2, 1, 3, 2, 2, 3, 3, 2, 0, 1, 4, 4, 0, 3, 4, 4, 4, 3, 0, 2, 4, 1,
       1, 3, 2, 1, 1, 4, 4, 3, 4, 1])

In [71]:
model = tf.keras.models.load_model("firstdlm/")

In [72]:
model.evaluate(test_data)

1/1 [==============================] - 9s 9s/step - loss: 677.8352 - accuracy: 0.6400


[677.835205078125, 0.6399999856948853]

In [73]:
import tensorflow as tf


def preprocess_image_to_tensor(filepath, target_size=(224, 224), normalize=True):
    """
    Preprocess an image for model prediction and return a normalized TensorFlow tensor.

    Parameters:
    - filepath (str): Path to the image file.
    - target_size (tuple): Desired image dimensions (height, width).
    - normalize (bool): Whether to normalize pixel values to [0, 1].

    Returns:
    - tf.Tensor: Preprocessed and normalized image tensor ready for model input.
    """
    # Load and decode the image
    img = tf.io.read_file(filepath)
    img = tf.image.decode_jpeg(img, channels=3)

    # Resize the image
    img = tf.image.resize(img, target_size)

    # Convert to float32
    img = tf.image.convert_image_dtype(img, tf.float32)

    # Normalize the image
    if normalize:
        img = img / 255.0  # Normalize pixel values to [0, 1]

    # Add batch dimension (e.g., from (height, width, channels) to (1, height, width, channels))
    img = tf.expand_dims(img, axis=0)

    return img

In [74]:
preprocess_image_to_tensor(
    "C:/Users/Vimal Manoharan/Desktop/AIML/Image Dataset/valid/boxing/1.jpg"
)

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.02745098, 0.02745098, 0.03529412],
         [0.02352941, 0.02352941, 0.03137255],
         [0.02352941, 0.02352941, 0.03137255],
         ...,
         [0.03137255, 0.03529412, 0.05490196],
         [0.02352941, 0.02745098, 0.04313726],
         [0.02352941, 0.02745098, 0.04313726]],

        [[0.02352941, 0.02352941, 0.03137255],
         [0.02352941, 0.02352941, 0.03137255],
         [0.02352941, 0.02352941, 0.03137255],
         ...,
         [0.03137255, 0.03529412, 0.05098039],
         [0.02745098, 0.03137255, 0.04705882],
         [0.02352941, 0.02745098, 0.04313726]],

        [[0.01960784, 0.01960784, 0.02745098],
         [0.02352941, 0.02352941, 0.03137255],
         [0.02352941, 0.02352941, 0.03137255],
         ...,
         [0.02745098, 0.03137255, 0.04705882],
         [0.02745098, 0.03137255, 0.04705882],
         [0.02745098, 0.03137255, 0.03921569]],

        ...,

        [[0.04313726, 0.0627451 , 

In [75]:
import tensorflow as tf


def preprocess_image(filepath, target_size=(256, 256), normalize=True):
    """
    Preprocess an image for model prediction and return a normalized TensorFlow tensor.

    Parameters:
    - filepath (str): Path to the image file.
    - target_size (tuple): Desired image dimensions (height, width).
    - normalize (bool): Whether to normalize pixel values to [0, 1].

    Returns:
    - tf.Tensor: Preprocessed and normalized image tensor ready for model input.
    """
    # Load and decode the image
    img = tf.io.read_file(filepath)
    img = tf.image.decode_jpeg(img, channels=3)

    # Resize the image
    img = tf.image.resize(img, target_size)

    # Convert to float32
    img = tf.image.convert_image_dtype(img, tf.float32)

    # Normalize the image
    if normalize:
        img = img / 255.0  # Normalize pixel values to [0, 1]

    # Return the tensor
    return img

In [80]:
image = preprocess_image(
    "C:/Users/Vimal Manoharan/Desktop/AIML/Image Dataset/valid/boxing/2.jpg"
)

In [81]:
model.predict(image)

ValueError: in user code:

    File "c:\Users\Vimal Manoharan\.conda\envs\new_env\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "c:\Users\Vimal Manoharan\.conda\envs\new_env\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\Vimal Manoharan\.conda\envs\new_env\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "c:\Users\Vimal Manoharan\.conda\envs\new_env\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "c:\Users\Vimal Manoharan\.conda\envs\new_env\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\Vimal Manoharan\.conda\envs\new_env\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential_2" is incompatible with the layer: expected shape=(None, 256, 256, 3), found shape=(32, 256, 3)


In [86]:
import tensorflow as tf
import numpy as np


# Preprocess the image
def preprocess_single_image(filepath, target_size=(256, 256), normalize=True):
    img = tf.io.read_file(filepath)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, target_size)
    img = tf.image.convert_image_dtype(img, tf.float32)
    if normalize:
        img = img / 255.0
    img = tf.expand_dims(img, axis=0)
    return img


# Load the model
model = tf.keras.models.load_model("firstdlm/")

# Predict a single image
image_path = "Sample Images/Test/javelin/3.jpg"
preprocessed_image = preprocess_single_image(image_path)
predictions = model.predict(preprocessed_image)

# Interpret the predictions
class_names = ["boxing", "bowling", "cricket", "golf", "javelin"]
predicted_probabilities = predictions[0]
predicted_class_index = np.argmax(predicted_probabilities)
predicted_class_name = class_names[predicted_class_index]

print(f"Predicted class: {predicted_class_name}")
print(f"Predicted probabilities: {predicted_probabilities}")

1/1 [==============================] - 0s 136ms/step
Predicted class: bowling
Predicted probabilities: [4.5825809e-07 9.9999952e-01 1.6282689e-12 5.4970351e-13 1.6804494e-08]


In [ ]:
models.Sequential([
    hub.KerasLayer("",trainable=False),
    tf.keras.layers.Dense(5,activation="softmax")
])